### PR TITLE
feat: added async support

### PR DESCRIPTION
**Pull request by peterdeme**
Async implementatiom by @Werded
I opened this PR because I have permission to run CI on it since I'm part of Stream.

### CODE REVIEW

**Comment by ferhatelmas** [comment]
@peterdeme I updated its configs, should be good now to run

**Comment by Werded** [comment]
is this something wrong with tests or it's something wrong on getstream server?

**Comment by ferhatelmas** [comment]
> is this something wrong with tests or it's something wrong on getstream server?

It's in staging environment, we're testing couple of other things. Will update today.

**Comment by Werded** [comment]
> > is this something wrong with tests or it's something wrong on getstream server?
> 
> It's in staging environment, we're testing couple of other things. Will update today.
 any progress?

**Comment by peterdeme** [comment]
@ferhatelmas can you create a new application and add the API key/secret combo to the repo secrets? 🙏

**Comment by ferhatelmas** [comment]
> @ferhatelmas can you create a new application and add the API key/secret combo to the repo secrets? pray

@peterdeme it's good to go to me but check the last commits for second look

**Review by ferhatelmas — APPROVED** [review]

**Pull request merged**
